### ISSUE TITLE
RuntimeError: The expanded size of the tensor (181) must match the existing size (211) at non-singleton dimension 0

### ISSUE THREAD

**Issue by kofuya** [microsoft/LLMLingua#36]
I use Qwen-7B ,then get error:
Traceback (most recent call last):
  File "/qwen/test.py", line 22, in <module>
    compressed_prompt = llm_lingua.compress_prompt(
  File "/usr/local/lib/python3.10/dist-packages/llmlingua/prompt_compressor.py", line 253, in compress_prompt
    context = self.iterative_compress_prompt(
  File "/usr/local/lib/python3.10/dist-packages/llmlingua/prompt_compressor.py", line 749, in iterative_compress_prompt
    past_loss[ready_end : end - 1] = loss
RuntimeError: The expanded size of the tensor (181) must match the existing size (211) at non-singleton dimension 0.  Target sizes: [181].  Tensor sizes: [211]

**Comment by iofu728** [comment]
Hi @kofuya,

Thanks for your support. Could you give me more context, like the original prompt.

**Comment by cornzz** [comment]
I have also gotten this error when trying to change `iterative_size`, I cannot say though when exactly or why this happens.
For example, compressing a prompt of size 4k at a rate of 0.33, iterative sizes of 100, 200, 300, 400, 500, 600, 700, 750, work, while iterative sizes of 800, 900, 1000, 2000, cause this error. Going higher above 2100 it works again.

Changing the rate also changes the iterative_size at which this error occurs, with higher compression the iterative_size at which it breaks is higher. It seems the iterative token-level prompt compression algorithm is broken.
